services:
  db:
    image: mysql:8
    platform: linux/x86_64
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: 1
    volumes:
      - ./db:/docker-entrypoint-initdb.d
    ports:
      - 3306:3306
    hostname: db

  app:
    build:
      context: app
    ports:
      - 8888:8888
    environment:
      - DATABASE_URL=mysql://root:@db:3306/codetest
      - PORT=8888
    depends_on:
      - db
    volumes:
      - ./app:/app
      - /app/node_modules
